/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Marva' at '1/15/17 6:08 PM' with Gradle 3.0
 *
 * @author Marva, @date 1/15/17 6:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
    	System.out.println("Printing in library class");
        return true;
    }
}
